name: "Run Allset Web Tests"
description: "Runs automated end-to-end or integration tests against a given environment."

inputs:
  environment:
    description: "The environment to run against. E.g. 'edge', or 'production'."
    required: true
  test_set:
    description: "The sub-set(directory) of tests to run. Defaults to `workflows` which includes all e2e smoke tests."
    required: false
    default: "workflows"

  package_token:
    description: "The Github packages token to use for private NPM Repos"
    required: true
  repo_token:
    description: "The SSH Deploy Token used to access the private AllsetHQ/web-tests repo"
    required: true

runs:
  using: "composite"

  steps:
    - name: Checkout web-tests
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ inputs.repo_token }}
        repository: AllsetHQ/web-tests

    - name: Change directory to action
      run: cd ${{ github.action_path }}
      shell: bash

    - name: Install NodeJS for Github Actions
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Authenticate with Github Packages
      run: npm set '//npm.pkg.github.com/:_authToken' ${{ inputs.package_token }}
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Install playwright
      run: npm i -g playwright@latest
      shell: bash

    - name: Run tests
      run: npm run test:${{ inputs.environment }}
      shell: bash
